Co-occurence matrix example

In [ ]:
# Step 1: Import necessary libraries
import numpy as np
from collections import defaultdict

In [ ]:
# Step 2: Define a simple text corpus
corpus = [
    "I like to learn NLP",
    "NLP is interesting",
    "NLP helps in text analysis",
    "Text analysis is important",
]


In [ ]:
# Step 3: Tokenize the corpus
tokens = [sentence.split() for sentence in corpus]

In [ ]:
tokens

[['I', 'like', 'to', 'learn', 'NLP'],
 ['NLP', 'is', 'interesting'],
 ['NLP', 'helps', 'in', 'text', 'analysis'],
 ['Text', 'analysis', 'is', 'important']]

In [ ]:
# Step 4: Define the context window size
window_size = 2  # You can adjust this based on your preference

# We set the context window size to 2, which means that we will
#consider two words to the left and two words to the right of the target word as its context.

In [ ]:
# Step 5: Initialize a co-occurrence matrix
vocab = set(word for sentence in tokens for word in sentence)
vocab_size = len(vocab)
co_occurrence_matrix = np.zeros((vocab_size, vocab_size))

# We initialize a co-occurrence matrix filled with zeros, where the rows and columns represent words in the vocabulary.

In [ ]:
co_occurrence_matrix

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# Step 6: Create the co-occurrence matrix
for sentence in tokens:
    for i, target_word in enumerate(sentence):
        # Determine the context window for each target word
        start = max(0, i - window_size)
        end = min(len(sentence), i + window_size + 1)
        context = sentence[start:end]

        # Increment co-occurrence counts within the context window
        target_index = list(vocab).index(target_word)
        for word in context:
            context_index = list(vocab).index(word)
            co_occurrence_matrix[target_index][context_index] += 1


#We iterate through the tokenized sentences, calculate the context for each target word,
#and increment the co-occurrence counts in the matrix based on the words in the context.


In [ ]:
# Step 7: Print the co-occurrence matrix
print("Co-occurrence Matrix:")
print(co_occurrence_matrix)


Co-occurrence Matrix:
[[1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 2. 1. 0. 0. 0. 0. 1. 0. 1. 1. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0. 3. 1. 1. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 1. 0. 1. 0. 0. 1. 0. 0. 2. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1.]]


# Neural Network example

In [ ]:
import numpy as np

# Step 1: Define the neural network architecture
class SimpleNeuralNetwork:
    def __init__(self):
        # Initialize weights and bias with random values
        self.weight = np.random.rand()
        self.bias = np.random.rand()

    def forward(self, x):
        # Forward propagation
        z = self.weight * x + self.bias
        return z

    def backward(self, x, dz):
        # Backward propagation to compute gradients
        dw = x * dz  # Gradient of loss with respect to weight
        db = dz      # Gradient of loss with respect to bias
        return dw, db

In [ ]:
# Step 2: Create an instance of the neural network
network = SimpleNeuralNetwork()


In [ ]:
# Step 3: Define input and target values
x = 2.0                # Input value
target = 4.0           # Target output value (desired prediction)

In [ ]:

# Step 4: Hyperparameters
learning_rate = 0.01   # Learning rate

In [ ]:
# Step 5: Training (forward and backward propagation)
for epoch in range(10):
    # Forward propagation
    prediction = network.forward(x)

    # Compute the loss (mean squared error)
    loss = 0.5 * (target - prediction) ** 2

    # Backward propagation
    dz = -(target - prediction)  # Partial derivative of loss with respect to z
    dw, db = network.backward(x, dz)

    # Update weights and bias
    network.weight -= learning_rate * dw
    network.bias -= learning_rate * db

    # Print the current loss
    print(f"Epoch {epoch + 1}: Loss = {loss:.4f}")

Epoch 1: Loss = 5.0667
Epoch 2: Loss = 4.5727
Epoch 3: Loss = 4.1269
Epoch 4: Loss = 3.7245
Epoch 5: Loss = 3.3614
Epoch 6: Loss = 3.0336
Epoch 7: Loss = 2.7379
Epoch 8: Loss = 2.4709
Epoch 9: Loss = 2.2300
Epoch 10: Loss = 2.0126


In [ ]:
# Step 6: Print the final weights and bias
print(f"Final weight: {network.weight:.4f}")
print(f"Final bias: {network.bias:.4f}")


Final weight: 0.7673
Final bias: 0.5594
