In [ ]:
import torch
import torch.nn as nn


# Import pprint, module we use for making our print statements prettier
import pprint
pp = pprint.PrettyPrinter()

##Part 1: Tensors

**Tensors** are PyTorch's most basic building block. Each tensor is a multi-dimensional matrix; for example, a 256x256 square image might be represented by a `3x256x256` tensor, where the first dimension represents color. Here's how to create a tensor:

## ** Creating Tensors **
Tensors are multi-dimensional arrays that can hold data of different types. You can create tensors in several ways:

**a. From a Python List**
You can create a tensor from a Python list:

In [ ]:
# Create a 1D tensor (vector)
tensor1d = torch.tensor([1, 2, 3])
tensor1d




tensor([1, 2, 3])

In [ ]:
list_1 = [
    [2,3,4],
    [4,5,6],
    [7,8,9]
]
tensor_list = torch.tensor(list_1)
tensor_list

tensor([[2, 3, 4],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Create a 2D tensor (matrix)
tensor2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# Create a 3D tensor
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
tensor3d

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

**b. 1. From a NumPy Array**

You can also convert a NumPy array into a PyTorch tensor:

In [ ]:
import numpy as np

numpy_array = np.array([1, 2, 3])
tensor_from_numpy = torch.tensor(numpy_array)

print(numpy_array)
print(tensor_from_numpy)




[1 2 3]
tensor([1, 2, 3])


In [ ]:
# Or directly from a NumPy array
tensor_direct = torch.from_numpy(numpy_array)
tensor_direct

tensor([1, 2, 3])

**b.2.Converting Tensors to NumPy Arrays**
You can convert PyTorch tensors to NumPy arrays and vice versa:

In [ ]:
tensor1d

tensor([1, 2, 3])

In [ ]:
# Convert PyTorch tensor to NumPy array
numpy_array = tensor1d.numpy()

numpy_array


array([1, 2, 3])

In [ ]:
# Convert NumPy array to PyTorch tensor
tensor_from_numpy = torch.from_numpy(numpy_array)
tensor_from_numpy

tensor([1, 2, 3])

**c. Creating Special Tensors**
PyTorch provides functions to create special tensors:

In [ ]:
# Create a tensor filled with zeros
zeros = torch.zeros(2, 3)
zeros



tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# Create a tensor filled with ones
ones = torch.ones(3, 2)
ones



tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
# Create an identity matrix
identity = torch.eye(3)
identity




tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
# Create a random tensor
random_tensor = torch.rand(3, 3)
random_tensor

tensor([[0.3067, 0.1583, 0.1309],
        [0.9366, 0.2614, 0.3171],
        [0.0413, 0.8007, 0.7239]])

**d. Accessing Tensor Properties**
You can access various properties of a tensor, such as its shape, data type, and more:



In [ ]:
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# Shape of a tensor
shape = tensor2d.shape
shape




torch.Size([2, 3])

In [ ]:
# Data type of a tensor
dtype = tensor2d.dtype
dtype



torch.int64

In [ ]:
# Number of dimensions
num_dimensions = tensor2d.dim()
num_dimensions



2

In [ ]:

# Total number of elements in the tensor
num_elements = tensor2d.numel()
num_elements

6

e. Tensor Operations
You can perform various mathematical operations on tensors, such as addition, subtraction, multiplication, and more:



In [ ]:
tensor1d

tensor([1, 2, 3])

In [ ]:
# Element-wise addition
result_add = tensor1d + tensor1d
result_add




tensor([2, 4, 6])

In [ ]:
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# Element-wise multiplication
result_mul = tensor2d * 2
result_mul



tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [ ]:
# Matrix multiplication
result_matmul = torch.matmul(tensor2d, torch.tensor([[2], [3], [4]]))
result_matmul

tensor([[20],
        [47]])

In [ ]:
# Element-wise addition
result_add = torch.add(tensor1d, tensor1d)
result_add




tensor([2, 4, 6])

In [ ]:
# Element-wise multiplication
result_mul = torch.mul(tensor1d, 2)
result_mul




tensor([2, 4, 6])

In [ ]:
# Element-wise subtraction
result_sub = torch.sub(tensor1d, torch.tensor([1, 1, 1]))
result_sub

tensor([0, 1, 2])

In [ ]:
# Element-wise division
result_div = torch.div(tensor1d, torch.tensor([2, 2, 2]))
result_div

tensor([0.5000, 1.0000, 1.5000])

**f. Indexing and Slicing Tensors**
You can access individual elements or slices of a tensor using indexing and slicing, just like you would with Python lists:

In [ ]:
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# Access an element
element = tensor2d[1, 2]
element




tensor(6)

In [ ]:
# Slice a tensor
slice = tensor2d[:, 1]  # All rows, second column
slice

tensor([2, 5])

**g. Moving Tensors to Different Devices**
PyTorch allows you to work with tensors on different devices, such as GPUs for faster computations. Here's how you can move tensors to GPUs:

In [ ]:
# Check if GPU is available
if torch.cuda.is_available():
    # Move a tensor to the GPU
    tensor_on_gpu = tensor1d.cuda()


**h. Reshaping Tensors**
You can change the shape of tensors using the .view() method:

In [ ]:
tensor1d

tensor([1, 2, 3])

In [ ]:
# Reshape a tensor
reshaped_tensor = tensor1d.view(1, 3)
reshaped_tensor




tensor([[1, 2, 3]])

In [ ]:
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# Flatten a tensor
flattened_tensor = tensor2d.view(-1)
flattened_tensor

tensor([1, 2, 3, 4, 5, 6])

**i. Basic Element-wise Functions**
PyTorch provides many built-in element-wise functions, such as torch.sin(), torch.cos(), torch.exp(), and torch.log(). These functions operate on tensors element by element:

In [ ]:
# Element-wise functions
result = torch.sin(tensor1d)
result


tensor([0.8415, 0.9093, 0.1411])

In [ ]:
result = torch.exp(tensor1d)
result

tensor([ 2.7183,  7.3891, 20.0855])

**j. Tensor Concatenation**
You can concatenate tensors along different dimensions:

In [ ]:
# Concatenate tensors along a dimension
concatenated_tensor = torch.cat([tensor1d, tensor1d], dim=0)  # Along rows
concatenated_tensor

tensor([1, 2, 3, 1, 2, 3])

In [ ]:
# Stacking along a new dimension
stacked_tensors = torch.stack([tensor1d, tensor1d])
stacked_tensors

tensor([[1, 2, 3],
        [1, 2, 3]])

**k. In-Place Operations**
Some operations can be performed in-place by adding an underscore to the method name. In-place operations modify the original tensor:

In [ ]:
# In-place addition
tensor1d.add_(2)  # Adds 2 to each element in tensor1d


tensor([3, 4, 5])

In [ ]:
tensor1d.mul_(3)

tensor([27, 36, 45])

In [ ]:
tensor1d.sub_(10)

tensor([ 8, 17, 26])

In [ ]:
tensor2d.add_(1)

tensor([[2, 3, 4],
        [5, 6, 7]])

**l. Saving and Loading Tensors**
You can save and load tensors using PyTorch's serialization functions:

In [ ]:
# Save a tensor to a file
torch.save(tensor1d, 'tensor.pt')

# Load a tensor from a file
loaded_tensor = torch.load('tensor.pt')
loaded_tensor

**m. Reduction Operations**

In [ ]:
# Sum of all elements
total_sum = torch.sum(tensor1d)
total_sum



tensor(51)

In [ ]:
# Mean of all elements
mean_value = torch.mean(tensor1d)
mean_value




RuntimeError: ignored

In [ ]:
# Create tensor1d with dtype=float32
tensor1d = torch.tensor([1, 2, 3], dtype=torch.float32)

# Compute the mean
mean_value = torch.mean(tensor1d)
print(mean_value)


tensor(2.)


In [ ]:
# Maximum element
max_value = torch.max(tensor1d)
max_value

tensor(3.)

In [ ]:
# Change the data type of tensor1d to float32 using .type()
tensor1d = tensor1d.type(torch.float32)


In [ ]:
# Change the data type of tensor1d to float32 using .type()
tensor1d = tensor1d.type(torch.float32)


In [ ]:
# Change the data type of tensor1d to float32 using .float()
tensor1d = tensor1d.float()

# Change the data type of tensor1d to double using .double()
tensor1d = tensor1d.double()

# Change the data type of tensor1d to int using .int()
tensor1d = tensor1d.int()
